#!/bin/sh

if test -n "$1"
then
    echo "Blessing $1"
    ./blessdriver $1
    echo "Signing blessings"
    gpg -b --digest-algo md5 --default-key "$2" "$1.bless"
    echo "Creating $1.blessings"
    cat "$1.bless" "$1.bless.sig" > "$1.blessings"
    echo "Padding $1.blessings"
    ./paddriver "$1.blessings"
    cat "$1.blessings.padded" $1 > "$1.driver"
    rm "$1.blessings" "$1.bless" "$1.bless.sig" "$1.blessings.padded"
else
    echo "Usage: $0 driver key-name"
fi
